### ISSUE TITLE
[Patchouli] Update Wildwood Quiver documentation for sneak-to-pick-up

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#138]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)
When firing any arrow type from the quiver they are not recoverable at all. If firing arrows from the inventory & not the quiver the arrows are retrievable. Firing arrows from an empty quiver still act fine and use durability of the quiver and can't be picked up as intended.

**Comment by duely** [comment]
This is unfortunately a side effect of the quiver, as it acts as an "infinite" arrow (meaning that they cannot be picked up). However, and this is most likely badly documented, you can pick up any living arrow (and in future any arrow you shoot with the bow and miss) not grown by the quiver by sneaking near it.

**Comment by duely** [comment]
I've tweaked the wording in the entry in 866eb74 which will hopefully clarify things better. Leaving this open for further feedback.

**Comment by duely** [comment]
Please have another look at this as of 3.0.3 and let me know if more information is needed.

**Comment by Cre8or** [comment]
Just tested this in 3.0.4, and the quiver is indeed able to pick up arrows (vanilla, living arrows and even modded ones), **but only if there is an empty slot in the quiver.**

This is not ideal, because it doesn't check whether the "used" slots have any space for the arrows. So if I have exactly one living arrow in every slot of the quiver, and I attempt to pick an additional one up, it fails - because it thinks there is no space for it.

Additionally, when the quiver decides that it can't pick an arrow up, it also prevents any other arrow stacks inside the player's inventory from picking the fired arrow up, even if they are not full. However I don't think this is directly linked to the quiver itself, seeing as the issue persists even after I drop it. Nonetheless, it's somewhat misleading, as this behaviour is not what one would expect.

**Comment by duely** [comment]
Thanks for the updated information! That's definitely something I forgot to change when I readjusted how it worked. I'll make a note of this for the next version.

**Comment by duely** [comment]
I'll be pushing some changes out to the testing group before I make the next release. The Arcane Archives release took a lot out of me and I've only just been able to sit down now with these issues (meanwhile procrastinating some other serious issues). If all goes well, I'll do a new release this week which will hopefully address this by giving the player the arrow instead (if the quiver is full) or dropping it on the ground beneath them otherwise.

**Comment by Cre8or** [comment]
Looking forward to it! Just don't burn yourself out, for your own sake. 😄

**Comment by duely** [comment]
@Cre8or If you're on the Mystic discord, I can give you the Testing role which will give you access to the latest pre-release builds for testing purpose if you're interested. And yeah, deliberately working on not burning out :D
