### ISSUE TITLE
Memory leak while rendering put-onned sylvan\wildroot armor

### ISSUE THREAD

**Issue by samakotleta** [MysticMods/Roots#154]
Windows task manager shows major javaw.exe memory leak (about 5-20 MB/s) while you're looking at player wearing these armors, for example in inventory or F5.

Was tested on latest forge with only Roots installed.

**Comment by duely** [comment]
So, as this is the first time anyone has reported this, and the fact of the matter is that the Sylvan/Wildroot armor functions identically to any other in-game model, I don't think this is likely to actually be an issue with Roots specifically. Otherwise we would have more reports. So, a little more information is needed:

What version of Forge precisely (latest does not suffice)? What version of Roots (latest does not suffice)? Is this multiplayer, or LAN-connected? What version of Java is the server running? What VM is the server running? What version of Java is the client running, and, if possible, what VM is the client running?

Is this consistent for your system? Has anyone else on the same server (if it is a server) had a similar issue? Are your graphics drivers up-to-date? Do you have any problems with modeled armor and creatures from other mods?

Could you also upload your `latest.log` and `debug.log` either to this ticket or to [Gist](http://gist.github.com) and link them?

**Comment by samakotleta** [comment]
Forge 14.23.5.2838,
Roots 3.0.4,
mystic world 1.3.2,
Java jre1.8.0_221.

Issue was tested both in singleplayer and multiplayer showing same results for me and my pals.

In case of multiplayer, memory leaking increases up to 5-50 mb/s while you looking at player wearing that armor, whether is your own character in inventory window or F5, or another player character.

All the same in case of singleplayer. Memory leaking also keeps happening even when game is paused while F5 and armor put-on.

Tested another modeled armors (thaumcraft, bewitchery) - there is no memory leaking.

logs:
https://gist.github.com/samakotleta/5ca1970d20eb1954788e2c583d801a31
