### ISSUE TITLE
Improve multiple-pouch handling, add dye potential

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#208]
They are great storage options but being able to color code them for quick use would be wonderful.

**Comment by duely** [comment]
At the moment, there are problems surrounding the fact that multiple apothecary pouches, while providing storage, will also cause the game confusion as to which pouch to consult (if there are multiples) when providing herbs.

By default it supplies from the one in the Baubles slot, but in addition to this we should probably come up with a system that iterates over all the available pouches looking for herbs, breaking when found, rather than just the first one and then saying "nothing here, you can't cast it!"

**Comment by duely** [comment]
(There is of course the fact that perhaps we only want herbs to be drawn from one pouch, but it becomes confusing to the user if this is not specifically or clearly stated. Some sort of "activation" to mark a pouch as the one being drawn from (and limiting the player to only one pouch/one equipped) might go a way to help with that.)
