### ISSUE TITLE
Windwall description error

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#213]
Minecraft: 1.12.2
Roots: 3.0.12
Forge: 14.23.5.2838
Book states "All creatures hostile to you are pushed away from the ritual location"
Reproduce: Spawn spider/Enderman nearby and it gets flung away regardless of hostility.
Suggestion: "All non-passive mobs are pushed away from the ritual location"

**Comment by duely** [comment]
Hm, excellent point. The problem is that it's nigh impossible to determine if a target is actively hostile towards the player or whether they're currently in passive -- constantly having issues making that differentiation, so there's usually a lot of confusing stuff. Pechs, for example, from Thaumcraft, would be flung away as they're considered IMobs... 

I'll re-word it.

**Comment by duely** [comment]
I've settled on "all potentially hostile creatures" for now, as that should cover the bracket. The system for determining hostile/non-hostile creatures should probably be unified with that of the Sanctuary spell, specifically -- hell, it needs to be unified with what I'm using in Dude! Where's my Horse? in order to determine which entities are summonable.

Potentially also this as well as Sanctuary's whitelist, could be extended to a whitelist/blacklist system for the general consideration of what is and isn't a "potentially hostile creature".
