### ISSUE TITLE
Multiplayer state changes for mossy -> non-mossy blocks don't update to all players

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/Roots#243]

**Comment by duely** [comment]
I need to test this more extensively because, as far as I can tell, the block state change *should* be working. The only possibility is that the video I saw with the bug happened before I rewrote the code; I'll need to test it in a multiplayer settings with a server & two clients -- my PC will love me.

**Comment by noobanidus** [comment]
This is as of yet unconfirmed.
