### ISSUE TITLE
[1.12.2] 'NoClassDefFoundError' Game Crash at startup.

### ISSUE THREAD

**Issue by Z-Tunic** [MysticMods/Roots#317]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Crash Report:
https://pastebin.com/j5RLcw9R

Mods: 9
Baubles-1.12-1.5.2
jei_1.12.2-4.15.0.279
Mantle-1.12-1.3.3.55
mysticallib-1.12.2-1.3.8
MysticWorld-1.12.2-1.4.5
Patchouli-1.0-20
Roots-1.12.2-3.0.14
TConstruct-1.12.2-2.12.0.157
TinkerToolLeveling-1.12.2-1.1.0

-----

Hopefully this is the right place... now this crash kinda puzzles me. The Game crashes at startup with the listed mods but it won't crash if I do either of these steps.

If I remove 'Tinker Tool Leveling'... no crash occurs at startup.

-OR-

If I remove 'Baubles'... no crash occurs at startup.

**Comment by duely** [comment]
Right, removing Baubles will prevent it, as the crash is caused by attempting to initialise a Bauble capability; if Baubles isn't installed, then the call just does nothing.

This definitely looks to be an issue with Tinker's Tool Leveling or Tinker's Construct. It's causing ItemStacks to be instantiated way, way early -- before all the mods have even loaded properly. Due to the way Mystical World and Roots' code work with MysticalLib, it expects that class instantiation won't happen until item registration, when MysticalLib is properly loaded.

[This line here](https://github.com/SlimeKnights/TinkersToolLeveling/blob/master/src/main/java/slimeknights/toolleveling/TinkerToolLeveling.java#L41) is statically instantiating a Modifier which is, through a series of chain reactions, resulting in an ItemStack being created, resulting in it comparing against a class, which is a subclass of a class that hasn't been loaded...

Yeah, weird. Definitely talk to Tinker's Tool Levelling.

**Comment by duely** [comment]
(I can work around it with an interface if absolutely necessary, but I'd really rather not.)

**Comment by duely** [comment]
[After a good night's sleep](https://github.com/SlimeKnights/TinkersToolLeveling/issues/105#issuecomment-538798138) I've decided to work on a potential solution from our end first.
