### ISSUE TITLE
[Roots 3] Spell ideas

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/Roots#35]
~~"Gust", boosts you 3-6 blocks into the air. Potentially blows back enemies. (Already exists as a more expensive future spell you mentioned.)~~
"Scatter", plant seeds in fertile ground in a 5x5 or 7x7 around the player. Seeds would be chosen from your off-hand for specifics, or at random from your inventory.
"Thaw", melt snow and ice into running water, hydrate farmland.
"Disarm", disarm nearby monsters. This would have a big impact on skeletons.
"Scythe", break grass in a 7x7x3 or a 10x10x5 radius. It would make looking for seeds that much more enjoyable. ***Additionally, it could harvest and replant all crops within that area.***
~~"Shed", cause one nearby animal to shed its skin (cow, llama), some wool (sheep), or some feathers (chickens). Such animals can only be shed after a cooldown has expire (hey there entity capability injection!)~~ (could still be useful as like a single-target animal harvest ritual)
"Fall", cause nearby leaves in a 10x10x10 or 7x7x7 radius to break and drop their bounty. Additionally causes all grass block to convert back into dirt.
"Till", if not included in "Scythe", would harvest and replant crops within a defined area.
"Blades", turn random top-level blocks of dirt in 10x10x5 area into grass (blades of grass).

**Comment by EpicSquid** [comment]
Waiting on spell rework

**Comment by duely** [comment]
Just some more thoughts I've had on these:

"Shed" technically already has a ritual associated with it (although I've yet to unlock it). I imagined that a single-target but aoe version would be a useful early way to get feathers without Quark installed. Although I would strongly recommend a SHED_COOLDOWN entity capability.

Spells for aoe or 3x3 harvesting (you right-click the center block) & replanting could probably leverage the ideas that TehNut's Harvest mod uses -- consuming the relevant seed item from the drops, firing the relevant forge event, then replacing the block state with the default for the crop/"age 0". That is, if you do replanting (making "Scattering" only conditionally useful).

"Disarm" may be OP for dealing with skeletons. This could be negated by having a short radius which means you have to get close to them in the first place. 

"Thaw" is really just a utility spell for cleaning up snow/breaking ice. I don't think it necessarily should be an expensive or difficult spell to make.

"Scattering" could be extended to cover saplings -- it could plant them pseudo-randomly but with a defined distance between them, allowing for accurate tree growth. I'm not sure what the proper algorithm would be.

"Till" could simply be a 3x3 (based on the center block) conversion of relevant blocks into farmland.

"Blades" could randomly turn dirt blocks into grass, meaning that there's a starting point for the grass to spread, but it would need more care.

***New spell idea(s)***

"Drizzle": a splashing sound as heavy rainfall suddenly falls around the player, hydrating farmland and giving a potential burst of additional growth ticks. It would need to be expensive enough that it couldn't be immediately spammed in order to function like a watering can.

"Candle": creates a temporary invisible light-casting entity at the targeted location that lasts a medium amount of time, then decays randomly or is destroyed when the chunk is unloaded. Could make mining useful.

**Comment by duely** [comment]
Priority: Scythe/Whirlwind

Additional: Compression

**Comment by Davoleo** [comment]
Isn't the candle spell quite similar to Fey Light? @duely

**Comment by duely** [comment]
Yeah, I think that one can be discarded.
