### ISSUE TITLE
Roots fairies causing OpenGL Error 1281 - "Invalid value"

### ISSUE THREAD

**Issue by Kachajal** [MysticMods/Roots#4]
[Here](https://paste.ee/p/E8e4T) is a pastebin of the logs. [Here](https://ufile.io/gtb2g) is a link to a save that has it happen.

The save happens to be near a fairy circle, but the error popped up then and again in seemingly random places in the past. Upon testing in a creative world, spawning a fairy and looking at it immediately causes the error to start. If I turn away from the fairy, the error no longer happens. 

My specs are:
i7-3630QM @ 2.40GHz
8GB RAM
Radeon HD7970M
Windows 7 x64.

**Comment by EpicSquid** [comment]
I'll keep an eye on this for roots 3.

**Comment by EpicSquid** [comment]
Have not seen this issue for roots 3, leaving it open for roots 2 as an known issue until roots 3 is released

**Comment by grompe** [comment]
The culprit seems to be in the way `ModelFairy.java` uses `OpenGlHelper.setLightmapTextureCoords()` right here:

https://github.com/EpicSquid/Roots/blob/788a4ec0c5cf13db8c636b73332d9c6c0204e97a/src/main/java/teamroots/roots/model/ModelFairy.java#L99

Why is the first parameter 1? I changed the line to
`OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240f, 240f);`
and the OpenGL error has stopped.

Doing this as I play Exoria modpack, which includes `roots-2-0.104`.

**Comment by duely** [comment]
@grompe Thanks for the information, apologies for the delay in responding to this. As was noted above, the issue will not be fixed as the Roots 2 codebase and mod have been entirely retired in favour of the latest version, but we'll make sure not to copy that error in going forwards.

**Comment by duely** [comment]
Thanks for the update! The fairies coming in 3.1 will hopefully not cause this issue with your fix :)
